DO $$
BEGIN
  IF EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = '${USERNAME}'
  ) THEN
      REASSIGN OWNED BY ${USERNAME} TO ${ADMIN_USERNAME};
      DROP OWNED BY ${USERNAME};
      DROP ROLE ${USERNAME};
  END IF;
END
$$;
