DO $$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = '${USERNAME}'
  ) THEN
    CREATE ROLE ${USERNAME} LOGIN PASSWORD '${PASSWORD}';
  ELSE
    ALTER ROLE ${USERNAME} PASSWORD '${PASSWORD}';
  END IF;
END
$$;
